### PR TITLE
Gracefully handle disconnect when reconnecting is in progress.

### PR DESCRIPTION
**Pull request by JimiC**

### CODE REVIEW

**Comment by sjmf** [comment]
That's interesting, I've not seen use of NodeJS.Timer in typescript before. Do we need to add any imports for this or is webpack just happy to bundle it in?

**Comment by JimiC** [comment]
The project makes use of `@types/node` (look in `package.json#devDepenedencies`) which provides type definitions for `nodejs`.

**Comment by sjmf** [comment]
Nice!

**Comment by JimiC** [comment]
Expanding on your inquiry, if you look at the [type definitions of `stompjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/stompjs/index.d.ts), it references `nodejs` type definitions, as it makes use of `NodeJs.Timer`, as well.

**Pull request merged**
