### PR TITLE
Update project to Angular 2 final via angular-cli.

### PR DESCRIPTION
**Pull request by JimiC**

### CODE REVIEW

**Comment by JimiC** [comment]
I didn't got the chance to ask you to review the README before you merge the PR.

Never the less, I decided to make the PR because `DefinitelyTyped` is taking too long to merge my `stompjs` typing PR. I can always submit another PR with the changes when those come out.

**Comment by JimiC** [comment]
Damn, `DefinitelyTyped` just merged my PR. 😛 
Talking about timing...

**Comment by JimiC** [comment]
@sjmf Probably you would want to issue a new release too. `v2` perhaps?

**Comment by sjmf** [comment]
Yes, that sounds like a good idea. I'll take a look at the README.md too when I get a moment.

**Comment by JimiC** [comment]
Also have a look at the `LICENSE` file. I took the liberty to add `Copyright (c) 2016 Sam Mitchell Finnigan and contributors`

**Comment by JimiC** [comment]
Also remember to update the `version` number in `package.json` when you gonna tag `v2`. Just a friendly reminder cause I always tend to forget it myself.

**Pull request merged**
